# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Timon's Technical Blog
email: tdegroot96@gmail.com
description: >
  Programming ideas, findings and examples. Mainly focussed on Magento 1 and 2.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.timpack.org" # the base hostname & protocol for your site
twitter_username: TimonGreat
github_username:  tdgroot
permalink: /:title

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from
